### ISSUE TITLE
`getBinaryDataBuffer()` for the Code node is undocumented

### ISSUE THREAD

**Issue by mark-monteiro** [n8n-io/n8n-docs#1648]
The [Get the binary data buffer cookbook](https://docs.n8n.io/code/cookbook/code-node/get-binary-data-buffer/) says that the `getBinaryDataBuffer()` should be used to access binary data from the Code node, but this method is completely undocumented other than in this cookbook, making it very confusing to use.

I think this method needs to be added to the documentation for [Built-in methods and variables](https://docs.n8n.io/code/builtin/). There should be clarification on the type and purpose of the two parameters (`itemIndex` and `binaryPropertyName`) as well as the method's return value.

**Comment by Joffcom** [comment]
That is an interesting request, my thought is the getBinaryDataBuffer() is a function / method rather than an expression which is what the proposed page references so it would be out of place.

We could maybe cross link to the cookbook page though to make it easier to find. I will have a chat with the rest of the docs team tomorrow and see if we can find a good balance for this.

**Comment by StarfallProjects** [comment]
Hi @mark-monteiro thanks for raising this. For now, we've added a link from the built-in methods landing page to the cookbook to make it more discoverable, and improved the info on that cookbook page.

Longer term, we'll look at:

- Creating a reference section for Code-node-only methods (I've created an internal ticket for this)
- Expanding the cookbook (an ongoing project)

I'm going to close this issue for now. To manage expectations a bit: I expect this quarter to focus on a mix of node creation docs, and possibly LangChain. I hope to revisit the Code section more heavily in the new year.
