### ISSUE TITLE
The Send email credentials docs is ... not really usefull

### ISSUE THREAD

**Issue by vilemduha** [n8n-io/n8n-docs#1914]
The documentation si really underwhelming. If n8n should be a no-code platform, there should be at least some instruction how to get the credential, at least from the most used platforms.

I was quite happy to see the progress on the n8n project and thought, hey, let's switch to an open-source project from Make.com - but what is actually great on Make is that you often don't need to enter any credentials, you just log into your google account or similar. If there's a need for api keys e.t.c. then there are super detailed instructions. 

I'd love to switch all automations our company does, which is quite a lot of workflows already, about 30 working workflows.

**Comment by StarfallProjects** [comment]
Hi @vilemduha is this the page you're referring to? https://docs.n8n.io/integrations/builtin/credentials/sendemail/

Our credentials pages definitely need work, and we're gradually moving them to a format that should give at least a starting point. You can view the template [here](https://github.com/n8n-io/n8n-docs/blob/main/document-templates/credentials.md).

However, assuming I've got the right page: the problem with this one is we really can't provide detailed instructions, because this node could work with a huge range of services.
