### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by classbasics** [n8n-io/n8n-docs#2028]
'You need to be understand' -> 'You need to understand'
https://docs.n8n.io/data/data-mapping/data-item-linking/

'data. Refer'  There is nothing to refer to
https://docs.n8n.io/data/data-mapping/data-item-linking/

the pairedItem object
https://docs.n8n.io/data/data-mapping/data-item-linking/item-linking-code-node/#paireditem-usage-example
it seems to me pairedItem is a key:value pair in every item object, not an object in its own right
however
https://docs.n8n.io/data/data-mapping/data-item-linking/item-linking-node-building/
does have pairedItem as an object
unfortunately
both approaches did not work for me, maybe insufficient information, or I just missed something important

'needs to be update ' -> 'needs to update '
https://docs.n8n.io/data/data-mapping/data-item-linking/item-linking-errors/#fix-for-info-for-expressions-missing-from-previous-node

**Comment by StarfallProjects** [comment]
Hi @classbasics thanks for this. We'll pick it up shortly - but you would also be welcome to submit a pull request :-)

**Comment by ayatnkw** [comment]
Hi @classbasics, thanks for the feedback! I went ahead and fixed the typos in the docs (see PR: https://github.com/n8n-io/n8n-docs/pull/2063) 

Regarding your question around `pairedItem`: 
Most nodes in n8n link output items to the input items automatically. But in specific cases, e.g. when using Code node, you might need to do this manually. And that's where `pairedItem` comes in handy. 

When **_using_** `pairedItem` in a node, it's typically a key-value pair because you're usually linking to a single input item. And that's what you'll see in the examples [here](https://docs.n8n.io/data/data-mapping/data-item-linking/item-linking-code-node/#paireditem-usage-example)

When you're **_building_** a node that supports this feature, `pairedItem` is an object because it can contain more than one piece of information which is what's explained [here](https://docs.n8n.io/data/data-mapping/data-item-linking/item-linking-node-building/). 
1. `item` which is the index of the input item that generated the output item
2. `input` which you can set if your node combines multiple inputs (optional) 
Note that this only applies when you're building a node programmatically. When building a declarative-style node, n8n handles this automatically. 

You mentioned that neither approaches work for you — what's your use-case? Are you trying to use it in a node or building your own node programatically? The [community forum](https://community.n8n.io/c/questions/12) is also a great place to post your questions, they're very helpful 😊

Hope this helps!
