### ISSUE TITLE
Changes for 'Creating your first workflow' - Option B

### ISSUE THREAD

**Issue by tanay1337** [n8n-io/n8n-docs#293]
@harshil1712 Proposed additions to the 'Automate Product Feedback with Typeform, Airtable, and Trello 📈' pathway:

- I think it would be helpful to add exactly what the datatype of the different fields in Typeform should be so that the reader can recreate it with the same fields. This will also help them use the example workflow that you provided out of the box. See example here: https://medium.com/n8n-io/automating-conference-organization-processes-with-n8n-ab8f64a7a520
- Same as above with Airtable. Screenshots of your Airtable would be helpful too. Would recommend setting instructions where they can copy your base (like in your n8n + Bravo Studio tutorial).

**Comment by maxtkacz** [comment]
Feedback:
- Users should not be copy pasting expressions in a first workflow tutorial, we need to teach them to use the expression editor (atleast at simplest, to drill down in a node to select an output)
- I'm torn between adding more explanation as to the why behind doing certain things as it's a pretty meaty piece already, which leads to my general thoughts below.
- There are some small things (like using Typeform's wording for a form "response" not submission) but can't easily comment here (would have to be inline)

My general thoughts are that this tutorial feels "heavy" if I'm thinking from a fresh user just trying to get their first workflow completed. Perhaps as a written piece this is unavoidable, but I feel like this pattern is happening to me a lot:
- I read a sentence which is verbally describing 2-3 UI steps; the font is serif. I then switch over to my n8n UI and always have to spend a good deal of mental energy (i.e. multiple seconds) trying to remember and map what I had to do (written in serif sentence form) into actions in the n8n ui.
- After doing that once, you start to look at the gif first which then has this back and forth and back between the instructions and the GIF, where my eye looks for the things to click (written form) and maps them to elements in the GIF. I then remember that and try to switch over to n8n editor to do those steps.

I'm not saying there is necessarily much that could be done to cut down the text. I know we follow this format for all tutorials so far on docs and I think it's ok for someone that has already gotten the "aha" from n8n (i.e. an onboarded power user) or for short things (credential setup). But given that creating a first workflow is crucial to user activation / onboarding; and that at this stage the user's attention is so fragile, I think we should simply ensure the video version is very strong. I know a non-trivial amount of work went into this text version - I do think we should keep it (basically polish up small tweaks + deploy) - some users won't mind a deeper longform text like this; but feel that wrapping up this text version to divert energy into the video is best strategic decision atm. 


**Sidenote, general feedback on tutorial titling** (since we link to a medium tutorial at end of article)

"Giving kudos to contributors with GitHub, Slack, and n8n 👏" is wordy and doesn't really tell me what I'm building

"Build a slack /slash command with n8n" feels more relatable to broader base of users and communicates a tangible result  (i.e. we're building a slack /slash command and for the example we'll build one that gives kudos) and conveys value of what user will create after completing the tutorial.
