### ISSUE TITLE
Instructions refer to broken github link

### ISSUE THREAD

**Issue by ryan-pypestream** [n8n-io/n8n-docs#881]
This line in the instructions is no longer valid:
git clone https://github.com/n8n-io/mkdocs-material-insiders.git mkdocs-material

Result:
fatal: repository 'https://github.com/n8n-io/mkdocs-material-insiders.git/' not found

**Comment by StarfallProjects** [comment]
Hiya Ryan! Thanks for being interested in contributing.

This link is intentional. The repo is private, and not accessible to external contributors. This is why the instructions are different for internal and external contributors. We can't make it public, as we have access to a closed-source version of the theme.

I'm going to close this issue, but if you encounter any problems when following the guidance for external contributors, feel free to open another issue.

**Comment by c-nv-s** [comment]
so how does somebody who is not 'internal' setup and run the documentation locally then? what are the actual instructions?
and do you not think it would be useful to clearly state in the README that the instructions are for internal team members only so as to avoid possibly wasting people's time?
and also perhaps ensure that there is a link to 'guidance for external contributors' before closing a ticket that has not been resolved?
there are many reasons people would want to self-host the documentation without necessarily intending to submit external contributions.
