### ISSUE TITLE
Missing option in interface

### ISSUE THREAD

**Issue by rosano** [n8n-io/n8n-docs#972]
From the [Merge docs](https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.merge/#inputs-with-different-numbers-of-items):

> If there are more items in one input than the other, the default behavior is to leave out the items without a match. Choose Add Option > Include Any Unpaired Items to keep the unmatched items.

It seems the 'Include Any Unpaired Items' option referenced is not in the interface; there is only 'Clash Handling', 'Multiple Matches', and 'Disable Dot Notation'.

**Comment by StarfallProjects** [comment]
Thanks for the report 🙏

'Include Any Unpaired Items' is available for 'Merge By Position', so that bit is correct. However, we should certainly add more options docs for the 'Merge by Field' section (which is the one with the options you mentioned) I've done a quick update to document clashes and multiple matches. Disable dot notation is documented within the UI in a tooltip, and is fairly niche I think, so leaving that out for now.

Resolved by: https://github.com/n8n-io/n8n-docs/pull/973
